AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Costco Gold Bar Alerting Service

Parameters:
  PhoneNumber:
    Type: String
    Description: Phone number to receive SMS alerts (E.164 format, e.g., +14155551234)
  SecretName:
    Type: String
    Default: costco-alerting-service/credentials
    Description: Name of the Secrets Manager secret containing Costco credentials

Globals:
  Function:
    Timeout: 120
    MemorySize: 1024
    Runtime: python3.11

Resources:
  CostcoCheckerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: costco-gold-bar-checker
      CodeUri: src/
      Handler: handler.lambda_handler
      Environment:
        Variables:
          PHONE_NUMBER: !Ref PhoneNumber
          COSTCO_SECRET_NAME: !Ref SecretName
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - sns:Publish
              Resource: '*'
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${SecretName}*'
      Events:
        ScheduledCheck:
          Type: Schedule
          Properties:
            Schedule: rate(15 minutes)
            Name: costco-gold-bar-check-schedule
            Description: Check Costco for gold bars every 15 minutes
            Enabled: true

  CostcoCredentialsSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref SecretName
      Description: Costco login credentials for the alerting service
      SecretString: '{"username":"YOUR_COSTCO_EMAIL","password":"YOUR_COSTCO_PASSWORD"}'

Outputs:
  CostcoCheckerFunction:
    Description: Lambda Function ARN
    Value: !GetAtt CostcoCheckerFunction.Arn
  ScheduleArn:
    Description: EventBridge Schedule ARN
    Value: !Sub 'arn:aws:events:${AWS::Region}:${AWS::AccountId}:rule/costco-gold-bar-check-schedule'
